In [1]:
import torch
from __future__ import print_function

torch.__version__

'1.7.0'

In [8]:
a = torch.ones(5)
print(a)
type(a)

tensor([1., 1., 1., 1., 1.])


torch.Tensor

In [9]:
b = a.numpy()
print(b)
type(b)

[1. 1. 1. 1. 1.]


numpy.ndarray

In [12]:
type(a)
print(type(a))
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [13]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

In [ ]:
torch.cuda.is_available()

In [ ]:
x = torch.empty(3,4)
print(x)
if torch.cuda.is_available():
    device = torch.device("cuda")
    # 在gpu上创建tensor
    y = torch.ones_like(x,device=device)
    print(y)
    x = x.to(device)
    print(x)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [17]:
torch.cuda.is_available()

True

In [24]:
x = torch.empty(3,4)
print(x)
if torch.cuda.is_available():
    device = torch.device("cuda")
    # 在gpu上创建tensor
    y = torch.ones_like(x,device=device)
    print(y)
    x = x.to(device)
    print(x)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[0.0000e+00, 1.4013e-45, 7.7052e+31, 7.2148e+22],
        [2.5226e-18, 6.4825e-10, 1.0072e-11, 7.7202e-10],
        [1.6692e-07, 4.0975e-11, 4.1955e-08, 2.9571e-18]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[0.0000e+00, 1.4013e-45, 7.7052e+31, 7.2148e+22],
        [2.5226e-18, 6.4825e-10, 1.0072e-11, 7.7202e-10],
        [1.6692e-07, 4.0975e-11, 4.1955e-08, 2.9571e-18]], device='cuda:0')
tensor([[1.0000e+00, 1.0000e+00, 7.7052e+31, 7.2148e+22],
        [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00]], device='cuda:0')
tensor([[1.0000e+00, 1.0000e+00, 7.7052e+31, 7.2148e+22],
        [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00]], dtype=torch.float64)
